export const PRICING_PLANS = [
  // {
  //   title: "Free Plan",
  //   price: "$0",
  //   priceNote: "",
  //   description:
  //     "Ideal for individual teachers or educators trying out our services.",
  //   features: [
  //     "50 Evaluations per Month",
  //     "Grading Theory Assignments",
  //     "Grading Coding Assignments",
  //     "Exam Grading",
  //     "AI Plagiarism Checker (Limited)",
  //     "Basic Rubric Generator",
  //     "Basic Reports",
  //   ],
  // },
  {
    title: "Free Plan",
    price: "$0",
    priceNote: "/user/month",
    description: "Perfect for small classes and individual tutors.",
    features: [
      "200 Evaluations per Month",
      "Grading Theory Assignments",
      "Grading Coding Assignments",
      "Exam Grading",
      "AI Plagiarism Checker",
      "Advanced Rubric Generator",
      "Detailed Reports",
      "Google Classroom Integration",
    ],
    missing: [
      "Dedicated support/ account manager",
      "Premium Support (Phone, Email, Chat)",
    ],
  },
  {
    title: "Premium Plan",
    price: "$39",
    priceNote: "/user/month",
    description:
      "Designed for larger classes, coaching institutes, and educational organizations.",
    features: [
      "1000 Evaluations per Month",
      "Grading Theory Assignments",
      "Grading Coding Assignments",
      "Exam Grading",
      "Advanced AI Plagiarism Checker",
      "Advanced Rubric Generator",
      "Detailed & Comprehensive Reports",
      "Google Classroom Integration",
      "Dedicated Support (Email & Chat)",
      // "Monthly Usage Analytics",
    ],
    missing: [
      "Dedicated account manager",
      "Premium Support (Phone, Email, Chat)",
    ],
  },
  {
    title: "School/University Plan",
    price: "Custom Pricing",
    priceNote: "",
    description:
      "Tailored for institutions needing detailed, large-scale evaluations",
    features: [
      "Custom Evaluation Limits",
      "Grading Theory Assignments",
      "Grading Coding Assignments",
      "Exam Grading",
      "Advanced AI Plagiarism Checker",
      "Customized Rubric Generator",
      "Highly Comprehensive, Custom Reports",
      "Advanced Google Classroom Integration",
      "Dedicated Account Manager",
      "Premium Support (Phone, Email, Chat)",
      // "Institutional Analytics Dashboard",
      // "Training & Onboarding",
    ],
  },
];
